# Generated by Django 3.2.7 on 2021-09-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=10)),
                ('driving_licence_no', models.CharField(max_length=20)),
                ('driving_licence_issued', models.CharField(max_length=50)),
                ('driving_licence_classes_A', models.BooleanField(default=False)),
                ('driving_licence_classes_B', models.BooleanField(default=False)),
                ('driving_licence_classes_C', models.BooleanField(default=False)),
                ('driving_licence_classes_D', models.BooleanField(default=False)),
                ('driving_licence_classes_E', models.BooleanField(default=False)),
                ('driving_licence_classes_T', models.BooleanField(default=False)),
                ('driving_licence_valid_to', models.DateField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.address')),
            ],
        ),
    ]
