# Generated by Django 3.2.5 on 2021-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driving_licence_classes_A',
            new_name='driving_licence_class_A',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driving_licence_classes_B',
            new_name='driving_licence_class_B',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driving_licence_classes_C',
            new_name='driving_licence_class_C',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driving_licence_classes_D',
            new_name='driving_licence_class_D',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driving_licence_classes_E',
            new_name='driving_licence_class_E',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driving_licence_classes_T',
            new_name='driving_licence_class_T',
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
