# Generated by Django 3.2.5 on 2021-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210928_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_licence_valid_color',
            field=models.CharField(default='green', max_length=50),
        ),
    ]
