# Generated by Django 3.2.5 on 2021-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='tel',
            field=models.CharField(max_length=13),
        ),
    ]
