# Generated by Django 3.2.7 on 2021-09-28 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 9, 28, 14, 26, 39, 687132, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='first_used_on_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default=datetime.datetime(2021, 9, 28, 14, 26, 53, 231877, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(default=datetime.datetime(2021, 9, 28, 14, 27, 29, 74024, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='rent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='car',
            name='stk_valid_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default=datetime.datetime(2021, 9, 28, 14, 27, 35, 834271, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
