# Generated by Django 3.2.7 on 2021-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210928_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='Barva'),
        ),
        migrations.AlterField(
            model_name='car',
            name='first_used_on_year',
            field=models.IntegerField(null=True, verbose_name='Rok uvedení do provozu'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=50, verbose_name='Výrobce'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=10, verbose_name='RZ:'),
        ),
        migrations.AlterField(
            model_name='car',
            name='stk_valid_to',
            field=models.DateField(null=True, verbose_name='STK platná do:'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=19, verbose_name='VIN:'),
        ),
    ]
